import { Container } from "@/components/ui/container";

const futureInputs = [
  {
    title: "Verified competition placements",
    description: "Results tied to documented, reviewable event records.",
  },
  {
    title: "Event quality",
    description: "Published context for the standard and structure of an event.",
  },
  {
    title: "Field strength",
    description: "A transparent account of the competitive field represented.",
  },
  {
    title: "Recent activity",
    description: "A visible window for which eligible performances are current.",
  },
  {
    title: "Consistency",
    description: "Repeat performances considered without hiding individual results.",
  },
  {
    title: "Discipline category",
    description: "Rules that keep unlike formats from being silently combined.",
  },
  {
    title: "Update history",
    description: "A public record of when and why a position changes.",
  },
] as const;

export function RankingsMethodology() {
  return (
    <section
      aria-labelledby="methodology-heading"
      className="technical-grid-dark bg-paper py-16 text-on-light sm:py-20 lg:py-24"
    >
      <Container>
        <div className="grid gap-10 lg:grid-cols-[minmax(18rem,0.58fr)_minmax(0,1.12fr)] lg:gap-16">
          <div>
            <p className="font-mono text-xs font-bold uppercase tracking-[0.17em] text-accent-dark">
              Methodology preview / Direction only
            </p>
            <h2
              id="methodology-heading"
              className="mt-4 max-w-xl text-balance font-display text-4xl font-black uppercase leading-[0.93] tracking-[-0.055em] sm:text-5xl"
            >
              Transparent inputs before a published model
            </h2>
            <p className="mt-6 max-w-xl text-base leading-7 text-muted-dark">
              A future ranking product should show the records it accepts, how
              categories stay comparable, and when decisions are revised.
              Those rules have not been created for this prototype.
            </p>

            <div className="mt-8 border-l-4 border-accent bg-on-light p-5 text-ink sm:p-6">
              <p className="font-mono text-xs font-bold uppercase tracking-[0.15em] text-accent">
                Presentation prototype / No active formula
              </p>
              <p className="mt-3 text-sm leading-6 text-muted">
                This prototype demonstrates presentation only. The displayed
                points and positions are fictional and were not generated by
                an official ranking model.
              </p>
            </div>
          </div>

          <div>
            <p className="border-t border-on-light/25 pt-4 font-mono text-xs font-bold uppercase tracking-[0.15em] text-muted-dark">
              Future considerations / Not currently scored
            </p>
            <ol className="mt-4 border-y border-on-light/20">
              {futureInputs.map((input, index) => (
                <li
                  key={input.title}
                  className="grid gap-3 border-b border-on-light/15 py-5 last:border-b-0 sm:grid-cols-[2.5rem_minmax(10rem,0.55fr)_minmax(0,1fr)] sm:items-start sm:gap-5"
                >
                  <span className="font-mono text-xs font-black text-accent-dark">
                    {String(index + 1).padStart(2, "0")}
                  </span>
                  <h3 className="text-sm font-black uppercase leading-5 tracking-[-0.01em]">
                    {input.title}
                  </h3>
                  <p className="text-sm leading-6 text-muted-dark">
                    {input.description}
                  </p>
                </li>
              ))}
            </ol>
          </div>
        </div>
      </Container>
    </section>
  );
}
